# Generated by Django 5.2.5 on 2025-08-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerFund',
            fields=[
                ('peer_fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('strategy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_symbol', models.CharField(max_length=10)),
                ('shares', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.fund')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('ticker_symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FundPerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('net_asset_value', models.FloatField()),
                ('return_percentage', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='portfolio.fund')),
            ],
            options={
                'unique_together': {('fund', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PeerPerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('net_asset_value', models.FloatField()),
                ('return_percentage', models.FloatField()),
                ('peer_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='portfolio.peerfund')),
            ],
            options={
                'unique_together': {('peer_fund', 'date')},
            },
        ),
    ]
