# Generated by Django 5.2.5 on 2025-08-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_peerfund_holding_stockprice_fundperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
